name: Build and test
on: [pull_request, push]

jobs:
  linux-build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        gnat_version: [^11]
        gprbuild_version: [^22]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - uses: alire-project/setup-alire@v1
      with:
        toolchain: gprbuild${{ matrix.gprbuild_version }} gnat_native${{ matrix.gnat_version }} --disable-assistant

    - run: sudo apt install gcc-arm-none-eabi

    - run: cd synth_plugin_macro && make

    - run: alr build
